---
title: "Stronger Enforcement on Speeding: Analyzing Traffic Violations in Toronto"
author: Cristina Su Lam
thanks: "Code and data supporting this analysis is available at: https://github.com/cristinaasu/BritishAirways_BookingAnalysis"
date: today
date-format: long
toc: true
fig_caption: yes
number-sections: true
bibliography: references.bib
format: pdf
---

# Introduction

The global aviation industry operates within a dynamic environment, necessitating a comprehensive understanding of the factors that influence booking completion rates among travelers. Hence our goal is to equip industry stakeholders with invaluable insights to inform strategic marketing initiatives and tailor offerings to meet customer expectations. This study focuses on travelers originating from Malaysia who consider British Airways as their preferred airline, presenting a unique opportunity to explore the intricacies of customer behavior within this specific context.

Previous research has highlighted the impact of factors like length of stay and flight duration on successful ticket bookings.1 Notably, a substantial proportion of tickets are booked for short flights, with just a one-day duration of stay at the destination.1 Additionally, individual studies have examined variables such as sales channel2, preference of in-flight meals3, and seat choices3, shedding light on their respective influences on booking completion. However, despite larger-scale investigations addressing the relationship between customer behavior and booking completion, research specific to the Malaysian context remains limited. Therefore, this study endeavors to fill this gap by incorporating all mentioned variables into a logistic regression model, with a particular emphasis on the local market.

# Methods

The research utilizes a Kaggle dataset containing 50,000 observations of flight booking data from British Airways. We narrow our focus to 7,174 observations of travelers originating from Malaysia, ensuring a more targeted analysis. This dataset has 12 predictors, including key variables such as length of stay, flight duration, sales channel, in-flight meals, and seat choices, central to our investigation. To uncover the customer behavior factors influencing the binary outcome booking completion, we employ a Generalized Linear Model's logistic regression framework with a logit link function.

This statistical analysis begins with constructing a full model incorporating all variables of the dataset. Subsequently, variable selection techniques are applied to identify the most relevant predictors, such as stepwise AIC and BIC. While both methods involve iteratively adding/removing variables to minimize the AIC/BIC, stepwise BIC imposes a stronger penalty for additional parameters. Moreover, the LASSO method is used, penalizing the absolute size of regression coefficients to shrink less important predictors to zero. Model diagnostics are then conducted to assess the quality of each model, involving identifying outliers, influential points using DFBETAS, and assessing multicollinearity with VIF, where a value greater than 5 indicates multicollinearity among predictors. To validate the models, cross-validation is performed to evaluate prediction accuracy using MAE, alongside utilizing ROC curves with AUC value to assess discriminatory ability. These validation techniques ensure the robustness and generalizability of our models for accurate predictions on unseen data.

In the event of detecting outliers and influential points, only outliers will be removed due to their potential to bias parameter estimates. Influential points, although characterized by extreme values on predictor variables, will not be removed as they do not significantly impact the response variable. Following outliers removal, the model selection, diagnostics, and validation processes will be repeated using the cleaned dataset.

The primary objective is to identify the best-performing model with a lower MAE for accuracy and higher AUC for discrimination. Additionally, we need to consider the significance of our predictors of interest in the model. Upon selecting the final model, we conduct Exploratory Data Analysis (EDA) using histograms and contingency tables to enhance comprehension of underlying data patterns. Overall, this approach ensures a systematic and rigorous analysis of the association between customer behavior factors and ticket booking completion.

# Results

## Model Selection, Diagnostics, Validation

We initiated by fitting the full model, encompassing all the 12 variables from our dataset. Subsequently, we employed the variable selection techniques, LASSO method and stepwise AIC and BIC. Interestingly, the LASSO Method did not identify any variables for inclusion, likely due to the high penalty imposed, resulting in all coefficients being reduced to zero. Consequently, we proceeded with the models generated by stepwise AIC and BIC. Below are the variables selected by each method:

1. Stepwise AIC: “sales_channel”,  “length_of stay”, “flight_duration”, “num_of_passengers”, “wants_extra_baggage”, “wants_preferred_seat”, “wants_in_flight_meals”

2. Stepwise BIC: “sales_channel”,  “length_of stay”, “flight_duration”, “wants_extra_baggage”, “wants_preferred_seat”, “wants_in_flight_meals”

Based on this, each model underwent thorough diagnostics and validation, which identified different numbers of influential points and outliers. As outlined in the methods section, we repeated the model selection, diagnostics, and validation processes using the cleaned dataset. Specifically, stepwise AIC and BIC procedures were re-ran with each cleaned dataset, yielding the same variables as above. Despite consistent variable selection, slight changes in model diagnostics and validation were observed. This iterative process enabled us to assess the impact of outlier removal on overall model performance, as summarized in Table 1.
```{r}




```

Drawing from the outcomes presented, the model derived from the Stepwise BIC approach with cleaned data is chosen. This decision is supported by several factors: the Stepwise BIC method penalizes complexity more heavily than AIC, prioritizing model simplicity and avoiding overfitting, which aligns with our research objective of identifying an accurate yet parsimonious model. The slightly lower MAE (Figue 1) suggests better prediction accuracy compared to other models, while maintaining a comparable AUC (Figure 2), indicating the model's ability to discriminate between completed and incomplete bookings. Moreover, all predictors of interest exhibit statistical significance, with p-values<0.001 (Appendix. Table 1), reinforcing the reliability of the model's predictive ability.

During model diagnostics, while influential points and outliers were identified, their prevalence was relatively lower compared to alternative models. For instance, variables such as length of stay exhibited a greater amount of influential points as stays increased, potentially representing special cases such as extended vacations, while flight duration displayed fewer influential points affecting booking completion (Figure 3). Moreover, the VIF<5 signifies the absence of multicollinearity issues in our chosen model (Appendix. Table 2). These results underscore the enhanced data quality and robustness achieved through some data cleaning procedures.

## Description of the Data
From our selected model, incorporating variables suggested by stepwise BIC from the cleaned dataset, we extracted significant insights into the distribution of customer behavior factors and their impact on booking completion. Examining the distributions depicted in Figure 4 and Appendix. Table 3, only 2456 bookings were completed, with the majority (2242) being made through the company’s online website. A large proportion of passengers opted for extra baggage (1968), a smaller proportion chose preferred seating, and nearly half of the customers preferred to forgo in-flight meals. Surprisingly, the substantial proportion of incomplete bookings underscores the need for further investigation into the factors affecting this response variable, we expect that our model can make a meaningful contribution in this regard.


In conclusion, the Stepwise BIC approach with cleaned data, tailored to represent the general customer base of the company in Malaysia, achieves an optimal balance between predictive accuracy, model simplicity, and robustness. This renders it the preferred choice for examining the core factors influencing booking completion among travelers originating from Malaysia and considering British Airways as their airline of choice.

# Discussion

## Final Model Interpretation

The final model uncovers insightful relationships between customer behavior factors and booking completion. Significantly, the odds of booking completion for customers using the mobile sales channel are 1.54 times lower (e^0.433 = 1.54) compared to those using the internet sales channel. This suggests potential challenges in the mobile application booking process. Conversely, additional services, such as extra baggage, preferred seating, and in-flight meals, positively impacts booking completion rates (Appendix. Table 1)

Moreover, the statistically significant coefficients underscore the robustness of these relationships, indicating that the observed effects are not due to random variation but reflect genuine associations, and reinforces the reliability of our findings. Overall, the model addresses our research question by elucidating the key determinants impacting booking completion rates, providing actionable insights for industry stakeholders to optimize the booking process and enhance customer satisfaction.

## Limitations

Acknowledging the stepwise BIC model with a cleaned dataset as our preferred choice for addressing the research question, it's crucial to note several limitations. While the AUC value is acceptable, a higher value closer to 1 would be preferable, improving the model's ability to distinguish class separation. Achieving this optimal value may require adjustments to the model architecture.

Despite efforts to remove outliers, a significant number of influential points and outliers persist in the dataset, potentially distorting the model's performance and predictions. Addressing them typically requires complex data preprocessing techniques and careful consideration of research’s goal.

Therefore, while acknowledging these limitations, it's important to interpret the results of the final model cautiously and consider their potential implications for decision-making within the aviation industry. Future research could explore alternative strategies for handling influential points and outliers to enhance the model’s predictive accuracy and robustness.

# Appendix

# References




